language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

install:
   - composer install

script: php vendor/bin/atoum -bf externals/tools/atoum/.bootstrap.atoum.php -d tests/units/
